[general]
static=yes
writeprotect=no

[from-internal]
exten => _1XXX,1,NoOp(Internal call to ${EXTEN} by ${CALLERID(num)})
 same => n,Set(RECORDING_FILE=/var/spool/asterisk/recording/manual-${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-from-${CALLERID(num)}-to-${EXTEN})
 same => n,MixMonitor(${RECORDING_FILE}.wav)
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,StopMixMonitor()
 same => n,Hangup()

exten => _9XXX,1,NoOp(Internal call to supervisor ${EXTEN} by ${CALLERID(num)})
 same => n,Set(RECORDING_FILE=/var/spool/asterisk/recording/manual-${STRFTIME(${EPOCH},,%Y%m%d-%H%M%S)}-from-${CALLERID(num)}-to-${EXTEN})
 same => n,MixMonitor(${RECORDING_FILE}.wav)
 same => n,Dial(PJSIP/${EXTEN},30)
 same => n,StopMixMonitor()
 same => n,Hangup()

[default]
exten => _XXXX,1,NoOp(Default ${EXTEN})
 same => n,Hangup()

[alertops-outbound]
exten => s,1,NoOp(AlertOps outbound)
 same => n,Stasis(alertops)
 same => n,Hangup()
